<?php
namespace App\Http\Views\Composers;
use Illuminate\View\View;

class TreesComposer {
  public function compose(View $view) {

    $data = ['Pando' => 'Pando, located in Utah, USA, is a clonal colony of quaking aspens, considered one of the oldest and largest living organisms on Earth. Estimated to be over 80,000 years old, it covers 106 acres and consists of genetically identical trees connected by a shared root system. Despite individual trees dying, the root system continues to regenerate, keeping the colony alive for millennia.',
    'Redwood' => 'Redwood trees (Sequoia sempervirens) are among the tallest and oldest trees on Earth. They can grow up to 379 feet (115 meters) tall, making them the tallest living organisms. Found primarily in coastal California, redwoods can live for over 2,000 years, with some specimens dating back to the 1st century BC. These trees thrive in moist, foggy environments and are known for their thick bark, which can be up to 12 inches (30 cm), offering protection from fire and pests.',
    'Eucalyptus' => 'Eucalyptus trees are a diverse group of over 700 species, mostly native to Australia. Known for their fast growth, some species, like the Mountain Ash, can reach up to 330 feet tall. Eucalyptus trees are famous for their aromatic leaves, which contain essential oils used in medicinal products. They are also fire-adapted, with many species having fire-resistant bark and the ability to regenerate after wildfires.',
    'Baobab' => 'The Baobab tree, native to Africa, is often called the "Tree of Life" due to its ability to store up to 32,000 gallons of water in its massive trunk, enabling it to survive in arid environments. These iconic trees can live for over a thousand years and are known for their distinct, swollen shape and broad, nutrient-rich fruits. Baobabs play a crucial role in local ecosystems and communities, providing food, shelter, and medicinal resources.',
    'Banyan' => 'The Banyan tree, native to the Indian subcontinent, is known for its unique growth pattern, where aerial roots grow down from the branches to form additional trunks. These trees can cover vast areas, with some individuals spreading across several acres. Revered in many cultures, the Banyan symbolizes immortality and is often found near temples or in sacred groves, providing shade and shelter to communities.',
    'Mangrove' => 'The Mangrove tree, found in coastal areas of tropical and subtropical regions, is known for its ability to thrive in salty, waterlogged environments. These trees have specialized roots that help filter salt and stabilize the coastal soil, reducing erosion and protecting shorelines from storms. Mangroves are essential for marine biodiversity, providing habitat for fish, crabs, and other aquatic species, while also acting as carbon sinks.',
    'Cedar' => 'The Cedar tree, known for its aromatic wood, is found in temperate regions of the northern hemisphere. Revered for its strength and durability, cedar wood is used in construction, furniture making, and aromatherapy. Cedars are often associated with ancient cultures and are symbols of longevity and resilience. These trees thrive in mountainous and coastal areas and support diverse wildlife.',
    'Maple' => 'The Maple tree, native to North America, is renowned for its beautiful fall foliage and the sap used to produce maple syrup. With its broad leaves and distinctive lobed shape, it thrives in temperate forests and contributes to the landscape’s ecological diversity. Maples are also valued for their wood, which is strong and often used in furniture and flooring.',
    'Acacia' => 'The Acacia tree, commonly found in tropical and subtropical regions, is known for its feathery, compound leaves and vibrant yellow or white flowers. Acacias are highly resilient, often thriving in arid climates, and many species have symbiotic relationships with ants, which protect the tree from herbivores. These trees are used for timber, resin, and are important in the ecosystems they inhabit, providing food and shelter for various animals.',
    'Sycamore' => 'The Sycamore tree, native to parts of Europe, Asia, and North America, is recognized for its broad, palmate leaves and distinctive peeling bark, which reveals patches of white and brown. Sycamores thrive in riverbanks and floodplains, and their wood is used in furniture-making and as a source of fuel. These trees are also known for their longevity, often reaching several hundred years of age.',
    'Palm' => 'The Palm tree, primarily found in tropical and subtropical regions, is known for its tall, slender trunk and fan-shaped or feather-like leaves. Palms provide essential resources for many cultures, including coconuts, dates, and palm oil. These trees also play a critical role in coastal ecosystems, protecting shorelines from erosion and supporting biodiversity in their native habitats.',
    'Jacaranda' => 'The Jacaranda tree, native to South America, is famous for its striking purple or blue flowers that create a vibrant, showy display in spring and summer. Jacarandas are commonly planted in urban landscapes and are admired for their aesthetic beauty. They thrive in warm climates and have a rapid growth rate, making them a popular choice for parks and streetscapes around the world.',
    'Kauri' => 'The Kauri tree, native to New Zealand, is one of the largest and longest-living tree species in the world. These giants can grow over 150 feet tall and live for more than 2,500 years. Kauris are highly prized for their dense, durable wood, which was historically used by Māori people for construction and carving. The trees are now protected, with some of the oldest individuals found in reserves and national parks.',
    'Ginkgo' => 'The Ginkgo tree, sometimes called the "Maidenhair Tree," is one of the oldest surviving tree species, dating back over 200 million years. Native to China, it is known for its unique fan-shaped leaves that turn bright yellow in autumn. Ginkgo trees are highly resistant to pollution and pests, making them ideal for urban areas. In traditional medicine, the leaves are used for memory enhancement, and the tree is revered for its endurance and resilience.',
    'Sakura' => 'The Sakura tree, native to Japan, is celebrated worldwide for its breathtaking springtime blossoms. The pale pink or white flowers bloom in early spring, creating scenic views that attract millions of visitors for the annual hanami festivals. Cherry blossoms symbolize renewal, fleeting beauty, and the transient nature of life, holding deep cultural significance in Japan and beyond.',
     'Oak' => 'The Oak tree is one of the most iconic and ancient trees, known for its immense strength and longevity. Native to the Northern Hemisphere, oaks can live for centuries and grow to great heights. The wood is highly valued for its strength and is used in furniture, flooring, and construction. Oak trees also support a rich variety of wildlife, with their acorns providing food for many animals, and their branches offering shelter for birds.',
     'Yew' => 'The Yew tree, known for its longevity and resilience, is native to temperate regions of Europe, Asia, and North America. It is often associated with ancient burial sites and sacred groves. Yews are slow-growing evergreen trees with dense, dark green foliage and red berries. The wood is highly prized for crafting, and the tree\'s longevity—some living for thousands of years—makes it a symbol of immortality in many cultures.'





   ];

    $view->with('trees',$data);
  }
}
?>
